apiVersion: apps/v1
kind: Deployment
metadata:
  name: worklark-website-production
  labels:
    app: worklark-website-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worklark-website-production
  template:
    metadata:
      labels:
        app: worklark-website-production
    spec:
      containers:
      - name: worklark-website-production
        image: gcr.io/worklark-218912/worklark-website:latest
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: production-database-credentials
                key: database_url
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.13
        command: ["/cloud_sql_proxy",
                  "-instances=<INSTANCE_CONNECTION_NAME>=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cluster-account-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cluster-account-credentials
          secret:
            secretName: cluster-account-credentials
---

kind: Service
apiVersion: v1
metadata:
  name: worklark-website-production
spec:
  selector:
    app: worklark-website-production
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
